name: Test

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:


jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        services:
            cassandra:
                image: cassandra
                ports:
                    - 9042:9042
                options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10
        steps:
            -   uses: actions/checkout@v3

            -   name: Run tests
                run: |
                    ./gradlew test